upload_max_filesize = 200M
post_max_size = 210M
memory_limit = 512M
max_execution_time = 300
max_input_time = 300

auto_prepend_file = /var/www/html/formularios/administrador/manejoJWT/api/auth.bootstrap.php

display_errors = On
error_reporting = E_ALL
log_errors = On
